In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('per.csv')
data.head()

NewsID                                              Title  \
0  843656  \r\nوزير علوم درجمع استادان نمونه: سن بازنشستگ...   
1  837144  \r\nگردهمايي دانش‌آموختگان موسسه آموزش عالي سو...   
2  436862  \r\nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌ن...   
3  227781  \r\nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي ...   
4  174187  \r\nوضعيت اقتصادي و ميزان تحصيلات والدين از مه...   

                                                Body           Date  \
0  \r\nوزير علوم در جمع استادان نمونه كشور گفت: ا...  \r\n138/5//09   
1  \r\nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجو...  \r\n138/5//09   
2  \r\nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي...  \r\n138/3//07   
3                                               \r\n  \r\n138/2//02   
4  \r\nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در ...  \r\n138/1//08   

          Time              Category    Category2  
0  \r\n0:9::18           \r\nآموزشي-   \r\nآموزشي  
1  \r\n1:4::11           \r\nآموزشي-   \r\nآموزشي  
2  \r\n1:0::03           \r\nآموزشي-   \r\nآموزشي  
3  \r\n1:3::42  \r\nاجتماعي-خانواده-  \r\nاجتماعي  
4  \r\n1:1::49           \r\nآموزشي-   \r\nآموزشي

In [4]:
with open('stopwords.txt', encoding='utf-8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 ':',
 '[',
 ']',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسیب پذیرند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن گاه',
 'آنان',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'اتفاقا',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احیاناً',
 'اخیر',
 'اخیراً',
 'اری',
 'از',
 'از آن پس',
 'از جمله',
 'ازاین رو',
 'ازجمله',
 'ازش',
 'اساسا',
 'اساساً',
 'است',
 'استفاد',
 'استفاده',
 'اسلامی اند',
 'اش',
 'اشتباها',
 'اشکارا',
 'اصلا',
 'اصلاً',
 'اصولا',
 'اصولاً',
 'اعلام',
 'اغلب',
 'افزود',
 'افسوس',
 'اقل',
 'اقلیت',
 'الا',
 'الان',
 'البته',
 'البتّه',
 'الهی',
 'الی',
 '

In [5]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [5]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

1495

In [6]:
import hazm
stemmer = hazm.Stemmer()

In [7]:
stemmer.stem('کتاب‌ها')

'کتاب'

In [8]:
from hazm import word_tokenize

In [9]:
dataset = pd.DataFrame(columns=['title_body', 'category'])
for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    dataset.loc[index]= {
        'title_body': ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

In [10]:
dataset.head()

title_body category
0  وزير علو درجمع استاد نمونه سن بازنشستگي استاد ...   آموزشي
1  گردهمايي دانش‌آموختگ موسسه آموز عالي سوره برگز...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  هماي يكروزه آسيب شناسي مفهو روابط عمومي بابلسر...  اجتماعي
4  وضعي اقتصادي ميز تحصيل والدين مهمترين عوامل مو...   آموزشي

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [13]:
X = vectorizer.transform(dataset['title_body'])

In [14]:
X

<10999x60814 sparse matrix of type '<class 'numpy.float64'>'
	with 1785147 stored elements in Compressed Sparse Row format>

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [17]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [18]:
len(y)

10999

In [19]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [20]:
np.shape(X)

(10999, 60814)

In [21]:
np.shape(y)

(10999,)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [24]:
from sklearn import svm

In [25]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [26]:
svmc.score(X_test, y_test)

0.8458181818181818

In [27]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87       260
           1       0.65      0.71      0.68       251
           2       0.85      0.78      0.82       248
           3       0.83      0.95      0.89       255
           4       0.87      0.91      0.89       239
           5       0.82      0.70      0.76       251
           6       0.83      0.72      0.77       244
           7       0.85      0.87      0.86       254
           8       0.84      0.88      0.86       252
           9       0.97      0.94      0.95       246
          10       0.97      0.95      0.96       250

    accuracy                           0.85      2750
   macro avg       0.85      0.85      0.85      2750
weighted avg       0.85      0.85      0.85      2750



In [28]:
print(confusion_matrix(y_test, y_pred))

[[234  10   1   4   0   0  10   1   0   0   0]
 [ 11 177  14   6   4   8   8  11   8   2   2]
 [  1  28 194   3   2   4   6   6   3   0   1]
 [  0   4   1 241   0   0   6   1   0   0   2]
 [  2   3   0   0 218   8   0   3   4   1   0]
 [  3  12   8   8  10 176   3   5  26   0   0]
 [ 21   8   4  22   2   4 176   5   0   0   2]
 [  4  13   0   1   6   4   2 221   0   3   0]
 [  1  12   2   0   6   5   2   2 221   1   0]
 [  0   1   2   2   2   4   0   3   1 231   0]
 [  1   5   2   2   0   2   0   1   0   0 237]]
